import "../globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import type { Metadata } from "next";
import Header from "../component/Header";
import { AuthChecker } from "../hooks/useAuth";
import RecoilRootWrapper from "../recoil/RecoilRootWrapper";
import QueryClientWrapper from "../query/QueryClientWrapper";

export const metadata: Metadata = {
  title: "Lolonoa",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1, user-scalable=no,maximum-scale=1,width=device-width",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <RecoilRootWrapper>
      <html lang="en" className="h-full w-full">
        <body className="h-full w-full">
          <div className="w-full h-full bg-navy">
            <div className="w-full p-[1rem] grid grid-cols-4 auto-rows-auto gap-x-[1rem] p-[8px] px-[1rem] border-box h-auto items-start m-0 bg-navy sm:grid-cols-8 lg:grid-cols-12 lg:gap-x-[2rem] lg:px-[2rem]">
              <Header className="row-start-1 col-start-1 col-span-4 mt-33px bg-navy sm:col-start-1 sm:col-span-8 lg:col-start-3 lg:col-span-8"></Header>
              <QueryClientWrapper>
                <AuthChecker />
                {children}
              </QueryClientWrapper>
            </div>
          </div>
        </body>
      </html>
    </RecoilRootWrapper>
  );
}
