import "../globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../component/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full w-full">
      <body className="h-full w-full">
        <div className="w-full h-full bg-navy">
          <div className="w-full p-[1rem] grid grid-cols-4 auto-rows-auto gap-x-[1rem] p-[8px] h-auto items-start m-0 bg-navy sm:grid-cols-8 lg:grid-cols-12 lg:gap-x-[2rem] lg:p-[2rem]">
            <Header className="row-start-1 col-start-1 col-span-4 mt-33px bg-navy sm:col-start-1 sm:col-span-8 lg:col-start-3 lg:col-span-8"></Header>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
