import "../globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../component/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full w-full">
      <body className="h-full w-full">
        <div className="h-full w-full grid grid-cols-12 auto-rows-auto gap-x-[2rem] p-[8px] h-auto items-start p-0 m-0 bg-navy">
          <Header className="row-start-1 col-start-3 col-span-8 mt-33px"></Header>
          {children}
        </div>
      </body>
    </html>
  );
}
