import "../globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { AuthChecker } from "../hooks/useAuth";
import RecoilRootWrapper from "../recoil/RecoilRootWrapper";
import QueryClientWrapper from "../query/QueryClientWrapper";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Lolonoa",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1, user-scalable=no,maximum-scale=1,width=device-width",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <RecoilRootWrapper>
      <html lang="en" className="h-full w-full">
        <body className="h-full w-full">
          <div className="h-full w-full flex justify-center items-center p-0 m-0 bg-navy">
            <QueryClientWrapper>
              <AuthChecker />
              {children}
            </QueryClientWrapper>
          </div>
        </body>
      </html>
    </RecoilRootWrapper>
  );
}
